/**
 * This file was generated by the Jeddict
 */ 

package db;

import configuracion.Constantes;
import fachade.DatoVariableRepository;
import fachade.EstratoRepository;
import fachade.IngresoRepository;
import fachade.PatrimonioRepository;
import java.io.Serializable;
import java.util.Date;
import javax.inject.Inject;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


@Entity
public class Estudiante implements Serializable { 
    
    @Inject @Transient private DatoVariableRepository datoVariableRepository;
    @Inject @Transient private EstratoRepository estratoRepository; 
    @Inject @Transient private PatrimonioRepository patrimonioRepository;
    @Inject @Transient private IngresoRepository ingresoRepository; 
    
    @Id @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic private String PEOPLE_CODE_ID;
    
    @Basic private String codigoPrograma;
    
    @Basic private String nombrePrograma;
    
    @Basic private String semestre;
    
    @Basic private int anyoLiquidacion;    
    
    @Basic private String Nombres;
    
    @Basic private String Apellidos;

    @Basic private int estrato;

    @Basic private int patrimonio;

    @Basic private int ingreso;
    
    @Basic private int ultimoPago; //pago mensual último anyo secundaria
    
    @Basic private int ultimoAnyoPago; //último año secundaria
    
    @Temporal(TemporalType.TIMESTAMP) private Date fechaActualizacion;
    
    @Basic private String actualizadoPor;
    
    @Basic private Boolean liquidar;

    public String getSemestre() {
        return semestre;
    }

    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }

    public String getCodigoPrograma() {
        return codigoPrograma;
    }

    public void setCodigoPrograma(String codigoPrograma) {
        this.codigoPrograma = codigoPrograma;
    }

    public String getNombrePrograma() {
        return nombrePrograma;
    }

    public void setNombrePrograma(String nombrePrograma) {
        this.nombrePrograma = nombrePrograma;
    }

    public Boolean getLiquidar() {
        return liquidar;
    }

    public void setLiquidar(Boolean liquidar) {
        this.liquidar = liquidar;
    }

    public Date getFechaActualizacion() {
        return fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActulizacion) {
        this.fechaActualizacion = fechaActulizacion;
    }

    public String getActualizadoPor() {
        return actualizadoPor;
    }

    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }

    public int getUltimoPago() {
        return ultimoPago;
    }

    public void setUltimoPago(int ultimoPago) {
        this.ultimoPago = ultimoPago;
    }

    public int getUltimoAnyoPago() {
        return ultimoAnyoPago;
    }

    public void setUltimoAnyoPago(int ultimoAnyoPago) {
        this.ultimoAnyoPago = ultimoAnyoPago;
    }

    public int getAnyoLiquidacion() {
        return anyoLiquidacion;
    }

    public void setAnyoLiquidacion(int anyoLiquidacion) {
        this.anyoLiquidacion = anyoLiquidacion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPEOPLE_CODE_ID() {
        return this.PEOPLE_CODE_ID;
    }

    public void setPEOPLE_CODE_ID(String PEOPLE_CODE_ID) {
        this.PEOPLE_CODE_ID = PEOPLE_CODE_ID;
    }

    public String getNombres() {
        return Nombres;
    }

    public void setNombres(String Nombres) {
        this.Nombres = Nombres;
    }

    public String getApellidos() {
        return Apellidos;
    }

    public void setApellidos(String Apellidos) {
        this.Apellidos = Apellidos;
    }

    public int getEstrato() {
        return this.estrato;
    }

    public void setEstrato(int estrato) {
        this.estrato = estrato;
    }


    public int getPatrimonio() {
        return this.patrimonio;
    }

    public void setPatrimonio(int patrimonio) {
        this.patrimonio = patrimonio;
    }


    public int getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(int ingreso) {
        this.ingreso = ingreso;
    }
    
    public double promedioIPC(){
        DatoVariable datoVariable;
        double temporal = 0;
        int contador = 0;
        for (int i = ultimoAnyoPago; i<anyoLiquidacion; i++){
            datoVariable = datoVariableRepository.findOptionalByAnyoAndNombre(i, Constantes.IPC);
            temporal += datoVariable.getValor();
            contador++;
        }
        
        if(contador > 0){
            return (temporal / contador);
        }
        
        return temporal;
    } 
    
    public int diferenciaAnyos(){
        if((anyoLiquidacion - ultimoAnyoPago)<= 10){
            return (anyoLiquidacion - ultimoAnyoPago);
        }else{
            return 10;
        }
    }
    
    public double liquidacionSecundaria(){
        return (4*ultimoPago*(Math.pow(1+promedioIPC(), diferenciaAnyos())));
    }
    
    public double liquidacionEstrato(){
        double smlv = 1;
        double porcentajeEstrato = 1;
        
        DatoVariable datoVariable = datoVariableRepository.findOptionalByAnyoAndNombre(anyoLiquidacion, "SMLV");        
        if(datoVariable != null){
            smlv = datoVariable.getValor();
        }                
        
        Estrato estratoTemporal = estratoRepository.findOptionalByAnyoAndEstrato(anyoLiquidacion, estrato);        
        if(estratoTemporal != null){
            porcentajeEstrato = estratoTemporal.getValorSMLV();
        }
        
        return smlv * porcentajeEstrato;        
    }
    
    public double liquidacionPatrimonio(){
        double smlv = 1;
        double porcentajePatrimonio = 1;
        DatoVariable datoVariable = datoVariableRepository.findOptionalByAnyoAndNombre(anyoLiquidacion, "SMLV");        
        if(datoVariable != null){
            smlv = datoVariable.getValor();
        }
        
        Patrimonio patrimonioTemporal = patrimonioRepository.
                findOptionalByDesdeGreaterThanAndHastaLessThanEqualsAndAnyo(patrimonio, patrimonio, anyoLiquidacion);
        if(patrimonioTemporal != null){
            porcentajePatrimonio = patrimonioTemporal.getValorSMLV();
        }
        
        return smlv * porcentajePatrimonio;
    }
    
    public double liquidacionIngreso(){
        double smlv = 1;
        double porcentajeIngreso = 1;
        DatoVariable datoVariable = datoVariableRepository.findOptionalByAnyoAndNombre(anyoLiquidacion, "SMLV");        
        if(datoVariable != null){
            smlv = datoVariable.getValor();
        }
        
        Ingreso ingresoTemporal = ingresoRepository.
                findOptionalByDesdeGreaterThanAndHastaLessThanEqualsAndAnyo(ingreso, ingreso, anyoLiquidacion);
        if(ingresoTemporal != null){
            porcentajeIngreso = ingresoTemporal.getValorSMLV();
        }
        
        return smlv * porcentajeIngreso;
    }
    
    public double derechoMatricula(){
        return (0.4*liquidacionSecundaria())+liquidacionEstrato()+liquidacionPatrimonio()+liquidacionIngreso();
    }
    
}
